apiVersion: v1
data:
  policy.yaml: "apiVersion: \"descheduler/v1alpha1\"\nkind: \"DeschedulerPolicy\"\n\
    strategies:\n  \"RemovePodsViolatingInterPodStatus\": \"0\"\n  \"RemovePodsViolatingInterPodStatus\"\
    : \"0\"\n  \"RemovePodsViolatingInterPodStatus\": \"0\"\n  \"RemovePodsViolatingInterPodStatus\"\
    : \"0\"\n"
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
