apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: needs-rebase
  name: needs-rebase
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: needs-rebase
  template:
    metadata:
      labels:
        app: needs-rebase
    spec:
      containers:
      - args:
        - --dry-run=false
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --github-token-path=/etc/github/oauth
        - --update-period=6h
        image: gcr.io/k8s-prow/needs-rebase:v20210915-24c2a7ab31
        imagePullPolicy: Always
        name: needs-rebase
        ports:
        - containerPort: 8888
          name: http
        volumeMounts:
        - mountPath: /etc/webhook
          name: hmac
          readOnly: true
        - mountPath: /etc/github
          name: oauth
          readOnly: true
        - mountPath: /etc/plugins
          name: plugins
          readOnly: true
      terminationGracePeriodSeconds: 180
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: oauth-token
      - configMap:
          name: plugins
        name: plugins
