apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-k8s-metrics-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: probe-k8s-metrics-server
  template:
    metadata:
      labels:
        run: probe-k8s-metrics-server
    spec:
      containers:
      - image: gcr.io/k8s-testimages/probemetrics-server:latest
        name: probe-k8s-metrics-server
