apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-2
  name: frontend-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-2
  template:
    metadata:
      labels:
        app: frontend-2
    spec:
      containers:
      - image: roguearus/frontend:v1.0
        imagePullPolicy: IfNotPresent
        name: frontend-2
        ports:
        - containerPort: 80
          protocol: TCP
