apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sinker
  name: sinker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sinker
  template:
    metadata:
      labels:
        app: sinker
    spec:
      containers:
      - args:
        - --kubeconfig=/etc/kubeconfig/config
        - --config-path=/etc/config/config.yaml
        - --job-config-path=/etc/job-config
        - --dry-run=false
        image: gcr.io/k8s-prow/sinker:v20210217-305381ec48
        name: sinker
        volumeMounts:
        - mountPath: /etc/kubeconfig
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/config
          name: config
          readOnly: true
        - mountPath: /etc/job-config
          name: job-config
          readOnly: true
      serviceAccountName: sinker
      volumes:
      - name: kubeconfig
        secret:
          defaultMode: 420
          secretName: kubeconfig
      - configMap:
          name: config
        name: config
      - configMap:
          name: job-config
        name: job-config
