apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubeconfig
  name: kubeconfig
  namespace: kubeconfig
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app: kubeconfig
  type: LoadBalancer
